# Generated by Django 4.2.15 on 2024-09-22 10:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='attributes_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.collection'),
        ),
    ]
