# Generated by Django 5.1.1 on 2025-04-18 20:37

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='media/products', validators=[store.validators.validate_image_size]),
        ),
    ]
