# Generated by Django 5.1.1 on 2025-05-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
