# Generated by Django 5.1 on 2024-08-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=['<django.db.models.fields.CharField>']),
        ),
    ]
