# Generated by Django 4.2.15 on 2024-09-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_collection_attributes_schema_collection_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
    ]
