# Generated by Django 5.1.1 on 2025-05-24 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
