# Generated by Django 4.2.15 on 2024-09-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
