# Generated by Django 4.2.15 on 2024-10-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('S', 'Readed'), ('U', 'Unread')], default='Unread'),
        ),
    ]
