# Generated by Django 4.2.15 on 2024-09-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptions',
            new_name='description',
        ),
    ]
