# Generated by Django 5.1.1 on 2025-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_review_options_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
