# Generated by Django 5.1.1 on 2025-07-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
    ]
