# Generated by Django 5.1.1 on 2025-07-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_customer_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
